name: Apply AWS Deployment
description: Apply AWS Deployment
on:
  workflow_run:
    workflows: ["Plan AWS Deployment"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3
